channels:
  - conda-forge
  - conda-forge/label/cf202003
dependencies:
  - glpk
  - ipopt=3.11.1=2
  - pip:
      - altair
      - matplotlib
      - numpy
      - pandas
      - pyomo
      - streamlit
